name: Package

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  # Always build & lint package.
  build-package:
    name: Build & verify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hynek/build-and-inspect-python-package@v2

  # Upload to real PyPI on GitHub Releases.
  release-pypi:
    name: Publish to pypi.org
    environment: release
    runs-on: ubuntu-latest
    needs: build-package
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write

    steps:
      - name: Download packages built by build-and-inspect-python-package
        uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist

      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
